name: 'Configure Vault Files'
description: 'Common actions to deploy an Hashicorp vault on an environment'
inputs:
  simple-user: 
    description: "Password of the vault service user"
    required: true
  secrets-environment: 
    description: "Secrets environment to create"
    required: true
  kv-name:
    description: 'Name of the Azure Keyvault containing the unseal key'
    required: true
  terraformstorage-key:
    description: 'Key to access storage of tfstate'
    required: true
  azuretenant-id:
    description: 'Azure tenant'
    required: true
  azuresuscription-id:
    description: 'Azure subscription where the infra will be deployed'
    required: true
  terraformclient-id:
    description: 'Client Id of the Azure App allowed to deploy in the subscription'
    required: true
  terraformclient-secret:
    description: 'Secret of the Azure App allowed to deploy in the subscription'
    required: true
  ansible-client-id:
    description: 'Client Id of the Azure App allowed used by ansible'
    required: true
  ansible-client-secret:
    description: 'Secret of the Azure App allowed used by ansible'
    required: true
  host-name:
    description: 'Name of the host running playbooks'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download vault config
      uses: actions/download-artifact@v2.0.10
      with:
        name: vault
        path: vault
    - name: Setup Ansible Hosts
      run: |
        echo ${{ host-name }} >> hosts
      shell: bash
      working-directory: vault
    - name: Add azure information for vault auto-unseal
      uses: falnyr/replace-env-vars-action@v1.2.1
      env:
        TERRAFORMSTORAGE_KEY:   ${{ inputs.terraformstorage-key }}
        AZURETENANT_ID:         ${{ inputs.azuretenant-id }}
        AZURESUSCRIPTION_ID:    ${{ inputs.azuresuscription-id }}
        TERRAFORMCLIENT_ID:     ${{ inputs.terraformclient-id }}
        TERRAFORMCLIENT_SECRET: ${{ inputs.terraformclient-secret }}
        KV_NAME:                ${{ inputs.kv-name }}
      with:
        filename: vault/config.hcl
    - name: Add azure information for ansible playbook
      uses: falnyr/replace-env-vars-action@v1.2.1
      env:
        AZURETENANT_ID:        ${{ inputs.azuretenant-id }}
        KV_NAME:               ${{ inputs.kv-name }}
        ENVIRONMENT:           ${{ inputs.secrets-environment }}
        ANSIBLE_CLIENT_ID:     ${{ inputs.ansible-client-id }}
        ANSIBLE_CLIENT_SECRET: ${{ inputs.ansible-client-secret }}
        KV_RESOURCE_GROUP: 
      with:
        filename: vault/ansible.yml
    - name: Add policy for custom path
      uses: falnyr/replace-env-vars-action@v1.2.1
      env:
        ENVIRONMENT: ${{ inputs.secrets-environment }}
      with:
        filename: vault/policy.hcl
    - name: Upload Ansible Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ansible
        path: vault
        
