name: 'Setup Vault'
description: 'Common actions to deploy an Hashicorp vault on an environment'
inputs:
  secrets-environment: 
    description: "Secrets environment to create"
    required: true
  kv-name:
    description: 'Name of the Azure Keyvault containing the unseal key'
    required: true
  terraformstorage-key:
    description: 'Key to access storage of tfstate'
    required: true
  azuretenant-id:
    description: 'Azure tenant'
    required: true
  azuresuscription-id:
    description: 'Azure subscription where the infra will be deployed'
    required: true
  terraformclient-id:
    description: 'Client Id of the Azure App allowed to deploy in the subscription'
    required: true
  terraformclient-secret:
    description: 'Secret of the Azure App allowed to deploy in the subscription'
    required: true
outputs:
  vault-token:
    description: "Root token of the vault"
    value: ${{ steps.setupvault.outputs.vaulttoken }}

runs:
  using: "composite"
  steps:
    - name: Download vault config
      uses: actions/download-artifact@v2.0.10
      with:
        name: vault
        path: vault
    - name: Add azure information for vault auto-unseal
      uses: falnyr/replace-env-vars-action@v1.2.1
      env:
        TERRAFORMSTORAGE_KEY:   ${{ inputs.terraformstorage-key }}
        AZURETENANT_ID:         ${{ inputs.azuretenant-id }}
        AZURESUSCRIPTION_ID:    ${{ inputs.azuresuscription-id }}
        TERRAFORMCLIENT_ID:     ${{ inputs.terraformclient-id }}
        TERRAFORMCLIENT_SECRET: ${{ inputs.terraformclient-secret }}
        KV_NAME:                ${{ inputs.kv-name }}
      with:
        filename: vault/config.hcl
    - name: Add policy for custom path
      uses: falnyr/replace-env-vars-action@v1.2.1
      env:
        ENVIRONMENT: ${{ inputs.secrets-environment }}
      with:
        filename: vault/policy.hcl
    - name: Upload Ansible Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ansible
        path: vault
        
