name: 'Deploy Vault Infrastructure'
description: 'Common actions to deploy an Hashicorp vault on an environment'
inputs:
  resources-suffix:
    description: 'Suffix to apply to the resource names (i.e. env-num)'
    required: true
  environment:
    description: 'Terraform workspace'
    default: "dev"
outputs:
  vault-vm-name:
    description: "Name (FQDN or IP) of the created VM"
    value: ${{ steps.getinfravalues.outputs.vmip }}
  simple-user:
    description: "Generated password for the created service user"
    value: ${{ steps.getinfravalues.outputs.simpleuser }}

runs:
  using: "composite"
  steps:
    - name: Download terraform Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: terraform
        path: terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.0
        terraform_wrapper: false
    - name: Terraform Plan
      id: plan
      # if: github.event_name == 'pull_request' # Not yet available for composite actions
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          terraform init
          terraform workspace select ${{ inputs.environment }}
          terraform plan -no-color -input=false -var 'suffix=${{ inputs.resources-suffix }}'
        fi
        exit 0
      # continue-on-error: true # Not yet available for composite actions
      shell: bash
      working-directory: terraform
    - name: Update Pull Request
      uses: actions/github-script@0.9.0
      # if: github.event_name == 'pull_request' # Not yet available for composite actions
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        script: |
          if (github.event_name !== 'pull_request') {
            return // Only available for pull requests
          }

          const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          terraform\n${{ steps.plan.outputs.stdout }}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - name: Terraform Plan Status
      # if: steps.plan.outcome == 'failure' # Not yet available for composite actions
      run: |
        if [[ "${{ steps.plan.outcome }}" == "failure" ]]; then
          exit 1
        fi
        exit 0
      shell: bash
    - name: Terraform Apply
      #if: ((inputs.environment == 'prod' && github.ref == 'refs/heads/main') || (inputs.environment != 'prod' && github.ref != 'refs/heads/main')) && github.event_name == 'push'
      run: |
        if [[ (("${{inputs.environment}}" == "prod" && "${{github.ref}}" == 'refs/heads/main') || ("${{inputs.environment}}" != "prod" && "${{github.ref}}" != 'refs/heads/main')) && "${{github.event_name}}" == "push" ]]; then
          terraform workspace select ${{ inputs.environment }}
          terraform apply -auto-approve -input=false
        fi
        exit 0
      shell: bash
      working-directory: terraform
    - name: 'Get Infra Outputs'
      id: getinfravalues
      # if: github.event_name == 'push' # Not yet available for composite actions
      run: |
        if [[ "${{github.event_name}}" == "push" ]]; then
          terraform workspace select ${{ inputs.environment }}
          vmip=$(terraform output -json -no-color vm1_ip_addr | jq -r .)
          simpleuser=$(terraform output -json -no-color simple_password | jq -r .value)
          echo ::set-output name=vmip::$vmip
          echo ::set-output name=simpleuser::$simpleuser
        fi
        exit 0
      shell: bash
      working-directory: terraform
